### ISSUE TITLE
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Invalid request

### ISSUE THREAD

**Issue by Damaskar** [andr1an/nic-api#26]
День добрый,

Последнее время вываливается ошибка на этапе получения токена

```python
Traceback (most recent call last):
  File "C:\Users\*\PycharmProjects\dns_change\check_dns.py", line 7, in <module>
    api.get_token(
  File "C:\Users\*\PycharmProjects\dns_change\venv\lib\site-packages\nic_api\__init__.py", line 238, in get_token
    token = self._session.fetch_token(
  File "C:\Users\*\PycharmProjects\dns_change\venv\lib\site-packages\requests_oauthlib\oauth2_session.py", line 366, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\*\PycharmProjects\dns_change\venv\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\*\PycharmProjects\dns_change\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\*\PycharmProjects\dns_change\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\Users\*\PycharmProjects\dns_change\venv\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Invalid request
```

Не проходит даже простая авторизация без каких-либо действий:

```python
from nic_api import DnsApi

app_login = "*******"
app_password = "********"
api = DnsApi(app_login, app_password)
api.get_token(
    username="*******",
    password="*******",
)
```

Данные для входа верны

**Comment by andr1an** [comment]
Здравствуйте,

Нужно больше информации. Попробуйте добавить `logging.getLogger("requests_oauthlib").setLevel(logging.DEBUG)` [после инициализации логгера](https://github.com/andr1an/nic-api/blob/master/nic_api/__init__.py#L36), возможно реквест по какой-то причине не подходит под [требования](https://www.nic.ru/help/oauth-server_3642.html#token).

Пакет `requests-oauthlib` не менялся с 29 января, так что вряд ли это он. Покажите вывод `pip freeze`, возможно `oauthlib` обновился, как раз версия 3.2.1 вышла 9 сентября.

**Comment by andr1an** [comment]
OAuth-сервер сервиса выдает «Invalid request» почти на любую ошибку, в том числе если забыть `/NIC-D` в логине пользователя указать, это `username` в `get_token()`. Не забыли случайно это?

**Comment by Damaskar** [comment]
Логин, пароль, данные к api верные, вопрос с обновлением oauthlib отпадает, изначально собрал из скриптов экзешники, они были неизменны и автономны, соответственно они перестали работать и я уже полез в код смотреть на предмет ошибок.
Логгирование попробую включить посмотреть на предмет дополнительной информации, отпишусь чуть позже. Спасибо.

**Comment by Damaskar** [comment]
Вот что из логгера вытащил:

```
DEBUG:requests_oauthlib.oauth2_session:Encoding `client_id` "*******************" with `client_secret` as Basic auth credentials.
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://api.nic.ru/oauth/token using method POST.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'password', 'username': '*******/NIC-D', 'password': '********', 'scope': '.+:/dns-master/.+', 'offline': '3600'}
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'timeout': None, 'auth': <requests.auth.HTTPBasicAuth object at ********************>, 'verify': True, 'proxies': None, 'cert': None}.
DEBUG:requests_oauthlib.oauth2_session:Request to fetch token completed with status 400.
DEBUG:requests_oauthlib.oauth2_session:Request url was https://api.nic.ru/oauth/token
DEBUG:requests_oauthlib.oauth2_session:Request headers were {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '115', 'Authorization': 'Basic *********'}
DEBUG:requests_oauthlib.oauth2_session:Request body was grant_type=password&username=*****%2FNIC-D&password=*******&scope=.%2B%3A%2Fdns-master%2F.%2B&offline=3600
DEBUG:requests_oauthlib.oauth2_session:Response headers were {'Server': 'nginx/1.18.0', 'Date': 'Fri, 16 Sep 2022 12:21:02 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '65', 'Connection': 'keep-alive', 'X-Request-Id': '*************', 'X-Kong-Upstream-Latency': '18', 'X-Kong-Proxy-Latency': '1', 'Via': 'kong/1.4.1'} and content {"error":"invalid_request","error_description":"Invalid request"}.
DEBUG:requests_oauthlib.oauth2_session:Invoking 0 token response hooks.
```

Попробовал так же с разными версиями oauth и request-oauth, к сожалению никаких изменений

**Comment by andr1an** [comment]
Очень странно, попробуйте с такими же данными и заголовками через `curl` (или `Invoke-WebRequest`, если есть только Windows с PowerShell). Если ошибка будет, надо писать в техподдержку NIC.RU, если нет — проблема где-то в Requests/OAuth-библиотеках.

**Comment by Damaskar** [comment]
Попробую на следующей неделе, по результатам отпишусь, спасибо.

**Comment by syslao** [comment]
Ошибка и логи 1в1, через postman отрабатывает
oauthlib опускал версию - не помогло

**Comment by Damaskar** [comment]
> Ошибка и логи 1в1, через postman отрабатывает oauthlib опускал версию - не помогло

Да, такая же история.

**Comment by andr1an** [comment]
@Damaskar @syslao Тут кажется нашли проблему, попробуйте с ветки https://github.com/andr1an/nic-api/pull/28

**Comment by Damaskar** [comment]
Очень странная история, похоже проблема была на стороне nic, ошибка исчезла на старых нетронутых билдах.
