### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by igroykt** [andr1an/nic-api#6]
Приветствую.
При вызове api.records() получаю следующую ошибку:

> Retrieving DNS records...
> Traceback (most recent call last):
>   File "clean.py", line 69, in <module>
>     records = api.records(SERVICE_ID, CERTBOT_DOMAIN)
>   File "/usr/local/lib/python3.6/dist-packages/nic_api/__init__.py", line 239, in records
>     return [parse_record(rr) for rr in _zone.findall('rr')]
>   File "/usr/local/lib/python3.6/dist-packages/nic_api/__init__.py", line 239, in <listcomp>
>     return [parse_record(rr) for rr in _zone.findall('rr')]
>   File "/usr/local/lib/python3.6/dist-packages/nic_api/models.py", line 47, in parse_record
>     raise TypeError('Unknown record type: {}'.format(record_type))
> TypeError: Unknown record type: AAAA

В DNS имеется одна запись типа AAAA.

**Comment by igroykt** [comment]
В качестве временного решения в models.py внес следующие изменения:
AAAA record type:
```
def parse_record(rr):
    """Parses record XML representation to one of DNSRecord subclasses.

    Reads <rr> tag, gets record type and passes <rr> internals to the specific
    DNS record model.

    Arguments:
        rr: an instance if ElementTree.Element: <rr> tag from API response;

    Returns:
        one of SOARecord, NSRecord, ARecord, CNAMERecord, MXRecord, TXTRecord.
    """
    # TODO: move this to the DNSRecord class as "from_xml"
    if not isinstance(rr, ElementTree.Element):
        raise TypeError('"rr" must be an instance of ElementTree.Element')

    record_classes = {
        'SOA': SOARecord,
        'NS': NSRecord,
        'A': ARecord,
        'AAAA' : AAAARecord,
        'CNAME': CNAMERecord,
        'MX': MXRecord,
        'TXT': TXTRecord,
    }

    record_type = rr.find('type').text

    if record_type not in record_classes:
        raise TypeError('Unknown record type: {}'.format(record_type))

    return record_classes[record_type].from_xml(rr)
```
AAAA record class:
```
class AAAARecord(DNSRecord):
    ttl = None

    def __init__(self, aaaa, ttl=None, **kwargs):
        super(AAAARecord, self).__init__(**kwargs)
        if ttl is not None:
            self.ttl = int(ttl)
            if self.ttl == 0:
                raise ValueError('Invalid TTL!')
        self.aaaa = aaaa

    def to_xml(self):
        root = ElementTree.Element('rr')
        if self.id:
            root.attrib['id'] = self.id
        _name = ElementTree.SubElement(root, 'name')
        _name.text = self.name
        if self.ttl is not None:
            _ttl = ElementTree.SubElement(root, 'tt')
            _ttl.text = str(self.ttl)
        _type = ElementTree.SubElement(root, 'type')
        _type.text = 'AAAA'
        _aaaa = ElementTree.SubElement(root, 'aaaa')
        _aaaa.text = self.aaaa
        return ElementTree.tostring(root, encoding=_XML_ENCODING)

    @classmethod
    def from_xml(cls, rr):
        if not isinstance(rr, ElementTree.Element):
            raise TypeError('"rr" must be an instance of ElementTree.Element')
        if rr.find('type').text != 'AAAA':
            raise ValueError('Record is not an AAAA record!')

        id_ = rr.attrib['id'] if 'id' in rr.attrib else None
        name = rr.find('name').text
        idn_name = rr.find('idn-name').text
        elem_ttl = rr.find('ttl')
        ttl = elem_ttl.text if elem_ttl is not None else None
        aaaa = rr.find('aaaa').text
        return cls(id_=id_, name=name, idn_name=idn_name, ttl=ttl, aaaa=aaaa)
```

**Comment by andr1an** [comment]
Здравствуйте!

Спасибо за обратную связь. Добавлю поддержку в следующей версии.

**Comment by andr1an** [comment]
Собрал новый релиз, если есть возможность — проверьте, пожалуйста. У меня опять деньги на аккаунте Nic.ru кончились.

**Comment by igroykt** [comment]
> 
> 
> Собрал новый релиз, если есть возможность — проверьте, пожалуйста. У меня опять деньги на аккаунте Nic.ru кончились.

Обновился. Работает. Спасибо 👍
